using System.Text.Json;
using System.Text.Json.Serialization;
using LiteratureMillionaire.API.Data;
using LiteratureMillionaire.API.Entities;
using LiteratureMillionaire.API.Services;
using Microsoft.EntityFrameworkCore;

namespace LiteratureMillionaire.API.Seed;

/// <summary>
/// The "Yaşıl Bakı" bank: 192 illustrated questions over 112 plants, each one a photograph and the
/// question of which plant it is.
///
/// Where it comes from. The scientific name of every plant was confirmed against Wikidata's taxon name,
/// the Azerbaijani name comes from that same record's az.wikipedia article, and the photograph from
/// NC State Extension's Plant Toolbox, which labels each picture with the part of the plant it shows.
/// Generated by tools/import/build_plant_questions.py; the sources are never read at runtime.
///
/// Why one plant carries several questions. The toolbox has the fruit, the flower and the leaf of the
/// same species, and each is a different question - a player who meets the plane tree twice, once by its
/// fruit and once by its flower, ends up knowing it. At most one picture per part, so the same white
/// blossom is never asked four times.
///
/// Why the wrong options are the careful part. Two cedars are indistinguishable in any photograph ever
/// taken; the first attempt at this bank dropped both, which was the wrong fix. A plant is never offered
/// as an option for a photograph of its own genus, of a species the catalogue recorded as confusable
/// with it, or - between conifers - of anything else with needles. A cedar beside a pomegranate, a fig
/// and a tulip is a question a person can answer.
///
/// First import only (see BankOwnership): the bank is filled when it is empty and never touched again, so a
/// question corrected or deleted in the panel's editor stays that way through every deployment. Correcting a
/// generated bank now means editing it in the panel, or - for a wholesale replacement - importing it again in
/// a later phase, not redeploying this file.
///
/// On that first import a question is identified by BookId + ImageUrl, which is unique because one photograph
/// makes exactly one question (the wording repeats, so it cannot be the key), and the whole import is one
/// transaction that only commits if the result is exactly ExpectedQuestionCount rows.
///
/// The opening campaign is created here, once, because a category with no campaign is invisible - the
/// home page lists what can be played, not what exists, so seeding the bank alone left nothing on screen.
/// It is created only if this book has no campaign at all, so changing its dates,
/// passing score or IsEnabled afterwards is an administrator's decision and survives every deployment.
/// Nothing else is switched off: quiz modes run in parallel.
/// </summary>
public static class YasilBakiSeed
{
    public const string BookTitle = "Yaşıl Bakı";
    public const string BookAuthor = "Bakı Abadlıq Xidməti MMC";
    public const string BookDescription = "Bakının ağacları, kolları və çiçəkləri: şəkildən bitkini tanımaq yarışı.";

    public const int ExpectedQuestionCount = 192;

    private static readonly DateOnly CampaignStart = new(2026, 9, 17);
    private static readonly DateOnly CampaignEnd = new(2026, 9, 30);
    private const int PassingScore = 8;
    private const string RewardTitle = "Bakı Abadlıq Xidməti MMC-dən hədiyyə";

    private const string ImagePrefix = "/question-images/plant-";
    private const string ResourceName = "LiteratureMillionaire.API.Seed.Data.yasil-baki-questions.json";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        Converters = { new JsonStringEnumConverter(allowIntegerValues: false) },
    };

    /// <summary>One generated question, as stored in the embedded JSON.</summary>
    public sealed record SeedQuestion(
        string SourceId,
        string Category,
        Difficulty Difficulty,
        string Text,
        string OptionA,
        string OptionB,
        string OptionC,
        string OptionD,
        string CorrectOption,
        string? Explanation,
        string ImageUrl,
        string ImageAltText,
        string ImageSource,
        string ImageLicense)
    {
        public string[] Options => new[] { OptionA, OptionB, OptionC, OptionD };

        public string Answer => Options["ABCD".IndexOf(CorrectOption[0], StringComparison.Ordinal)];
    }

    private sealed record BankFile(IReadOnlyList<SeedQuestion> Questions);

    /// <summary>Reads the embedded bank. Throws when it is missing or unreadable.</summary>
    public static IReadOnlyList<SeedQuestion> LoadQuestions()
    {
        using var stream = typeof(YasilBakiSeed).Assembly.GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException($"Embedded question bank '{ResourceName}' was not found.");
        var file = JsonSerializer.Deserialize<BankFile>(stream, JsonOptions)
            ?? throw new InvalidOperationException("Yaşıl Bakı bank could not be read.");
        return file.Questions;
    }

    /// <summary>Problems that make the bank unusable. Empty when it is valid.</summary>
    public static IReadOnlyList<string> Validate(IReadOnlyList<SeedQuestion> questions)
    {
        var problems = new List<string>();

        if (questions.Count != ExpectedQuestionCount)
        {
            problems.Add($"Expected {ExpectedQuestionCount} questions, found {questions.Count}.");
        }

        // Every difficulty has to be able to fill a round on its own.
        foreach (var difficulty in Enum.GetValues<Difficulty>())
        {
            var actual = questions.Count(q => q.Difficulty == difficulty);
            if (actual < QuizRules.EasyPerQuiz + QuizRules.MediumPerQuiz + QuizRules.HardPerQuiz)
            {
                problems.Add($"Only {actual} {difficulty} questions; a round cannot be varied.");
            }
        }

        foreach (var duplicate in questions.GroupBy(q => q.SourceId, StringComparer.Ordinal).Where(g => g.Count() > 1))
        {
            problems.Add($"Duplicate SourceId {duplicate.Key}.");
        }

        // The picture is the idempotency key, so two questions may never share one.
        foreach (var duplicate in questions.GroupBy(q => q.ImageUrl, StringComparer.OrdinalIgnoreCase).Where(g => g.Count() > 1))
        {
            problems.Add($"Duplicate image {duplicate.Key}.");
        }

        foreach (var question in questions)
        {
            var id = question.SourceId;

            if (string.IsNullOrWhiteSpace(question.Text)) problems.Add($"{id}: question text is empty.");
            if (question.CorrectOption is not ("A" or "B" or "C" or "D")) problems.Add($"{id}: correct option '{question.CorrectOption}' is not A-D.");
            if (question.Options.Any(string.IsNullOrWhiteSpace) || question.Options.Distinct(StringComparer.Ordinal).Count() != 4)
            {
                problems.Add($"{id}: options are not four distinct values.");
            }

            if (!question.ImageUrl.StartsWith(ImagePrefix, StringComparison.Ordinal)
                || !question.ImageUrl.EndsWith(".webp", StringComparison.Ordinal))
            {
                problems.Add($"{id}: image '{question.ImageUrl}' is not a plant asset.");
            }

            if (string.IsNullOrWhiteSpace(question.ImageAltText) || question.ImageAltText.Length > 300) problems.Add($"{id}: alt text is missing or too long.");
            // Attribution has to travel with a picture published under a licence that requires it.
            if (string.IsNullOrWhiteSpace(question.ImageSource)) problems.Add($"{id}: no image source.");
            if (string.IsNullOrWhiteSpace(question.ImageLicense)) problems.Add($"{id}: no image licence.");

            // The alt text is read aloud by a screen reader before the options, so it may not give the
            // answer away - which is why it says "a plant" and never which one.
            if (question.ImageAltText.Contains(question.Answer, StringComparison.CurrentCultureIgnoreCase))
            {
                problems.Add($"{id}: alt text names the answer.");
            }

            if (question.Explanation is { } why && !why.Contains(question.Answer, StringComparison.CurrentCultureIgnoreCase))
            {
                problems.Add($"{id}: the explanation does not name the plant the question is about.");
            }
        }

        return problems;
    }

    public static async Task SeedAsync(ApplicationDbContext db, CancellationToken ct = default)
    {
        var seed = LoadQuestions();
        var problems = Validate(seed);
        if (problems.Count > 0)
        {
            throw new InvalidOperationException("Yaşıl Bakı seed data is invalid:\n" + string.Join("\n", problems));
        }

        await using var transaction = await db.Database.BeginTransactionAsync(ct);

        var quizModeId = await QuizModeSeed.GetIdAsync(db, QuizModeSlugs.YasilBaki, ct);

        var book = await db.Books.FirstOrDefaultAsync(b => b.Title == BookTitle, ct);
        if (book is null)
        {
            book = new Book
            {
                Title = BookTitle,
                Author = BookAuthor,
                Description = BookDescription,
                CoverImageUrl = string.Empty,
                IsActive = true,
            };
            db.Books.Add(book);
            await db.SaveChangesAsync(ct);
        }


        // The panel owns this bank once it has questions (see BankOwnership): filled here once, never
        // reconciled again, so an edit or a deletion made in the editor survives every deployment.
        if (await BankOwnership.AlreadyFilledAsync(db, book.Id, ct))
        {
            await transaction.CommitAsync(ct);
            return;
        }

        var existing = await db.Questions.Where(q => q.BookId == book.Id).ToListAsync(ct);
        var byImage = new Dictionary<string, Question>(StringComparer.OrdinalIgnoreCase);
        foreach (var row in existing)
        {
            // A row of this book without a picture, or a second row on the same picture, can only come
            // from outside this seeder; it is left unmatched and removed below.
            if (row.ImageUrl is { } url)
            {
                byImage.TryAdd(url, row);
            }
        }

        var now = DateTime.UtcNow;
        var keep = new HashSet<int>();

        foreach (var q in seed)
        {
            if (byImage.TryGetValue(q.ImageUrl, out var row))
            {
                keep.Add(row.Id);
                Apply(row, q, quizModeId);
                continue;
            }

            var added = new Question { BookId = book.Id, CreatedAt = now };
            Apply(added, q, quizModeId);
            db.Questions.Add(added);
        }

        var stale = existing.Where(row => !keep.Contains(row.Id)).ToList();
        if (stale.Count > 0)
        {
            db.Questions.RemoveRange(stale);
        }

        await db.SaveChangesAsync(ct);

        var total = await db.Questions.CountAsync(q => q.BookId == book.Id, ct);
        if (total != ExpectedQuestionCount)
        {
            // Rolls the whole reconciliation back rather than leave the bank in a state nobody reviewed.
            throw new InvalidOperationException(
                $"After reconciling, '{BookTitle}' holds {total} questions, expected {ExpectedQuestionCount}.");
        }

        // Every question here carries a photograph, so a round is ten of them - the quota is not a target
        // to hit out of a mixed bank, it is simply what this bank is.
        // Any campaign of the book, whatever its dates: once one exists, campaigns are the admin panel's, and a date
        // changed there must not bring the seeded one back on the next deployment.
        var campaignExists = await db.MonthlyCampaigns.AnyAsync(c => c.BookId == book.Id, ct);
        if (!campaignExists)
        {
            db.MonthlyCampaigns.Add(new MonthlyCampaign
            {
                QuizModeId = quizModeId,
                BookId = book.Id,
                ImageQuestionsPerQuiz = QuizRules.QuestionsPerQuiz,
                StartDate = CampaignStart,
                EndDate = CampaignEnd,
                PassingScore = PassingScore,
                RewardTitle = RewardTitle,
                IsEnabled = true,
            });
            await db.SaveChangesAsync(ct);
        }

        await transaction.CommitAsync(ct);
    }

    /// <summary>Copies one generated row onto a question, leaving Id, BookId and CreatedAt alone.</summary>
    private static void Apply(Question row, SeedQuestion q, int quizModeId)
    {
        row.QuizModeId = quizModeId;
        row.Text = q.Text.Trim();
        row.OptionA = q.OptionA;
        row.OptionB = q.OptionB;
        row.OptionC = q.OptionC;
        row.OptionD = q.OptionD;
        row.CorrectOption = q.CorrectOption[0];
        row.Difficulty = q.Difficulty;
        row.Category = q.Category;
        row.Explanation = q.Explanation;
        row.ImageUrl = q.ImageUrl;
        row.ImageAltText = q.ImageAltText;
        row.ImageSource = q.ImageSource;
        row.ImageLicense = q.ImageLicense;
    }
}
